### PR TITLE
check if hasVibrator

### PR DESCRIPTION
**Pull request by pinpong**
prevent crashes on devices without vibrate support

### CODE REVIEW

**Comment by Willham12** [comment]
see https://github.com/junina-de/react-native-haptic-feedback/issues/72

**Comment by pinpong** [comment]
@mkuczera 

https://developer.android.com/reference/android/os/VibrationEffect#createPredefined(int)

Android Q is not Android O

Please revert your changes in the PR

**Comment by mkuczera** [comment]
Hi, sorry, just wanted to comment and was distracted. I will adjust today some places to match the methods to the corresponding vibrate actions on android with a proper fallback down to api level 26. @pinpong

**Comment by bradzickafoose** [comment]
Heh heh.

**Pull request merged**
