### PR TITLE
Export feedback types type

### PR DESCRIPTION
**Pull request by pvinis**

### CODE REVIEW

**Comment by mrousavy** [comment]
The `HapticFeedbackTypes` union type is already exported because of the `declare module`.

**Comment by pvinis** [comment]
I'm not sure if that works. I couldn't access the type without exporting it manually.

**Comment by woodrufs** [comment]
I second @mrousavy that these are already exported. @pvinis, you do not need to export the type from a declaration file. I have imported the type in a project of mine without issues like so:
```
import Haptic, { HapticFeedbackTypes } from "react-native-haptic-feedback";
```

**Comment by mkuczera** [comment]
Closing due to invalid.

**Pull request closed without merging**
